In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/sales_data.csv")
df.head()

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,39,male,Cairo,Headphones,Electronics,1,1760,1760
1,2,nada,63,female,Suez,Monitor,Electronics,2,11489,22978
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,1290,1290
3,4,Laila,65,male,Cairo,Monitor,Electronics,4,6621,26484
4,5,Laila,39,female,Tanta,Headphones,Electronics,3,1366,4098

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         10000 non-null  int64
 1   customer_name    10000 non-null  str
 2   customer_age     10000 non-null  int64
 3   customer_gender  10000 non-null  str
 4   city             10000 non-null  str
 5   product          10000 non-null  str
 6   category         10000 non-null  str
 7   quantity         10000 non-null  int64
 8   unit_price       10000 non-null  int64
 9   total_price      10000 non-null  int64
dtypes: int64(5), str(5)
memory usage: 781.4 KB

In [3]:
df.describe()

          order_id  customer_age      quantity    unit_price    total_price
count  10000.00000  10000.000000  10000.000000  10000.000000   10000.000000
mean    5000.50000     41.415800      2.993100   8973.231500   26598.447000
std     2886.89568     13.836461      1.421075  12317.228491   42269.466174
min        1.00000     18.000000      1.000000    150.000000     150.000000
25%     2500.75000     29.000000      2.000000    777.000000    2234.250000
50%     5000.50000     42.000000      3.000000   2826.500000    7191.500000
75%     7500.25000     53.000000      4.000000   9993.000000   29070.000000
max    10000.00000     65.000000      5.000000  39994.000000  199530.000000

In [4]:
df.columns

Index(['order_id', 'customer_name', 'customer_age', 'customer_gender', 'city',
       'product', 'category', 'quantity', 'unit_price', 'total_price'],
      dtype='str')

In [5]:
df.nunique()

order_id           10000
customer_name          8
customer_age          48
customer_gender        2
city                   8
product                5
category               1
quantity               5
unit_price          6253
total_price         7705
dtype: int64

In [6]:
df.sample(10)

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
7126,7127,Youseef,47,male,Aswan,Monitor,Electronics,1,3086,3086
3441,3442,Mona,47,female,Luxor,Mouse,Electronics,1,363,363
7097,7098,nada,23,male,Tanta,Keyboard,Electronics,5,590,2950
898,899,Youseef,64,male,Giza,Keyboard,Electronics,5,1310,6550
8223,8224,nada,29,female,Giza,Laptop,Electronics,5,25421,127105
879,880,nada,59,female,Giza,Monitor,Electronics,1,5076,5076
7891,7892,Mona,28,male,Mansoura,Headphones,Electronics,5,515,2575
388,389,Laila,60,female,Giza,Headphones,Electronics,1,2038,2038
8989,8990,nada,26,male,Cairo,Keyboard,Electronics,1,610,610
1134,1135,Omar,50,male,Suez,Monitor,Electronics,5,5394,26970

In [7]:
df.isna().sum()

order_id           0
customer_name      0
customer_age       0
customer_gender    0
city               0
product            0
category           0
quantity           0
unit_price         0
total_price        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["customer_name"].value_counts()

customer_name
Laila      1290
Ali        1268
Ahmed      1264
Youseef    1263
Sara       1261
Omar       1225
Mona       1220
nada       1209
Name: count, dtype: int64

In [10]:
df["city"].value_counts()

city
Cairo         1307
Alexandria    1269
Giza          1267
Aswan         1263
Tanta         1248
Mansoura      1233
Luxor         1210
Suez          1203
Name: count, dtype: int64

In [11]:
df_clean = df.copy()

In [12]:
df_clean.loc[0, "customer_age"] = 150
df_clean.loc[1, "customer_gender"] = None
df_clean.loc[2, "unit_price"] = -500
df_clean.loc[3, "city"] = "paris"
df_clean.head()

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,150,male,Cairo,Headphones,Electronics,1,1760,1760
1,2,nada,63,NaN,Suez,Monitor,Electronics,2,11489,22978
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,-500,1290
3,4,Laila,65,male,paris,Monitor,Electronics,4,6621,26484
4,5,Laila,39,female,Tanta,Headphones,Electronics,3,1366,4098

In [13]:
df_clean[df_clean["customer_age"] > 100]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,150,male,Cairo,Headphones,Electronics,1,1760,1760

In [14]:
df_clean[df_clean["unit_price"] < 0]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,-500,1290

In [15]:
df_clean[df_clean["customer_gender"].isna()]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
1,2,nada,63,NaN,Suez,Monitor,Electronics,2,11489,22978

In [16]:
valid_cities = [
    "Cairo",
    "Alexandria",
    "Giza",
    "Mansoura",
    "Tanta",
    "Aswan",
    "Luxor",
    "Suez"]
df_clean[~df_clean["city"].isin(valid_cities)]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
3,4,Laila,65,male,paris,Monitor,Electronics,4,6621,26484

In [17]:
valid_gender = [
    "male",
    "female"]
df_clean[~df_clean["customer_gender"].isin(valid_gender)]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
1,2,nada,63,NaN,Suez,Monitor,Electronics,2,11489,22978

In [18]:
print(
    df_clean[
    df_clean["quantity"] * df_clean["unit_price"] != df_clean["total_price"]
    ]
)
print(
df_clean[
    df_clean["unit_price"] < 0
    ]
)

   order_id customer_name  customer_age customer_gender  city   product  \
2         3           Ali            61          female  Suez  Keyboard

      category  quantity  unit_price  total_price
2  Electronics         1        -500         1290
   order_id customer_name  customer_age customer_gender  city   product  \
2         3           Ali            61          female  Suez  Keyboard

      category  quantity  unit_price  total_price
2  Electronics         1        -500         1290

In [19]:
df_clean[(df_clean["customer_age"] > 60) &
(df_clean["customer_gender"] == "female")]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,-500,1290
34,35,Youseef,65,female,Aswan,Mouse,Electronics,2,715,1430
51,52,Mona,65,female,Giza,Laptop,Electronics,5,28716,143580
54,55,Laila,65,female,Cairo,Keyboard,Electronics,4,1411,5644
59,60,Mona,63,female,Alexandria,Monitor,Electronics,5,7752,38760
...,...,...,...,...,...,...,...,...,...,...
9875,9876,Laila,62,female,Aswan,Mouse,Electronics,5,672,3360
9886,9887,Laila,62,female,Luxor,Monitor,Electronics,5,6676,33380
9903,9904,nada,64,female,Suez,Laptop,Electronics,2,29821,59642
9914,9915,Laila,62,female,Alexandria,Laptop,Electronics,1,30719,30719
9994,9995,Ali,65,female,Aswan,Headphones,Electronics,1,3750,3750

In [20]:
df_clean["city"] == "Cairo"

0        True
1       False
2       False
3       False
4       False
        ...
9995     True
9996    False
9997    False
9998    False
9999    False
Name: city, Length: 10000, dtype: bool

In [21]:
df_clean[
    df_clean["city"] == "Cairo"
]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,150,male,Cairo,Headphones,Electronics,1,1760,1760
39,40,Ahmed,52,female,Cairo,Headphones,Electronics,3,2311,6933
54,55,Laila,65,female,Cairo,Keyboard,Electronics,4,1411,5644
63,64,Mona,38,female,Cairo,Headphones,Electronics,1,4371,4371
72,73,nada,54,male,Cairo,Headphones,Electronics,5,4528,22640
...,...,...,...,...,...,...,...,...,...,...
9975,9976,nada,25,male,Cairo,Mouse,Electronics,5,708,3540
9979,9980,Ahmed,27,female,Cairo,Monitor,Electronics,5,11188,55940
9980,9981,Omar,59,female,Cairo,Mouse,Electronics,5,781,3905
9991,9992,Sara,26,female,Cairo,Headphones,Electronics,5,3359,16795
9995,9996,nada,59,female,Cairo,Monitor,Electronics,4,9811,39244

In [22]:
df_clean["customer_age"].median()

np.float64(42.0)

In [23]:
median_age = 42

In [24]:
df_clean.loc[
    df_clean["customer_age"] > 100,
    "customer_age"
    ] = median_age

In [25]:
df_clean[df_clean["customer_age"] > 100]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [26]:
gender_dict = {
    "Ahmed": "male",
    "Sara": "female",
    "Omar": "male",
    "Mona": "female",
    "Ali": "male",
    "Youseef": "male",
    "nada": "female",
    "Laila": "female"
}
gender_from_name = df_clean["customer_name"].map(gender_dict)

In [27]:
df_clean["customer_gender"] = df_clean["customer_gender"].fillna(gender_from_name)

In [28]:
df_clean["customer_gender"].isna().sum()

np.int64(0)

In [29]:
df_clean[df_clean["customer_gender"].isna()]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [30]:
gender_dict

{'Ahmed': 'male',
 'Sara': 'female',
 'Omar': 'male',
 'Mona': 'female',
 'Ali': 'male',
 'Youseef': 'male',
 'nada': 'female',
 'Laila': 'female'}

In [31]:
df_clean[df_clean["unit_price"] < 0]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,-500,1290

In [32]:
df_clean["unit_price"].min()

np.int64(-500)

In [33]:
age_median = df_clean[(df_clean["customer_age"] >= 0 ) & (df_clean["customer_age"]<= 100)]["customer_age"].median()

In [34]:
df_clean.loc[
    ~(
        (df_clean["customer_age"] >= 0) &
        (df_clean["customer_age"] <= 100)
    ),
    "customer_age"
] = age_median

In [35]:
df_clean[
    ~(
        (df_clean["customer_age"] >= 0) &
        (df_clean["customer_age"] <= 100)
    )
]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [36]:
df_clean["customer_age"].min(),df_clean["customer_age"].max()

(np.int64(18), np.int64(65))

In [37]:
df_clean["customer_gender"].value_counts(dropna=False)

customer_gender
female    5018
male      4982
Name: count, dtype: int64

In [38]:
df_clean[~df_clean["customer_gender"].isin(["male","female"])]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [39]:
df_clean["city"].value_counts(dropna=False)

city
Cairo         1306
Alexandria    1269
Giza          1267
Aswan         1263
Tanta         1248
Mansoura      1233
Luxor         1210
Suez          1203
paris            1
Name: count, dtype: int64

In [40]:
df

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,39,male,Cairo,Headphones,Electronics,1,1760,1760
1,2,nada,63,female,Suez,Monitor,Electronics,2,11489,22978
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,1290,1290
3,4,Laila,65,male,Cairo,Monitor,Electronics,4,6621,26484
4,5,Laila,39,female,Tanta,Headphones,Electronics,3,1366,4098
...,...,...,...,...,...,...,...,...,...,...
9995,9996,nada,59,female,Cairo,Monitor,Electronics,4,9811,39244
9996,9997,Laila,58,male,Aswan,Keyboard,Electronics,3,510,1530
9997,9998,nada,49,male,Alexandria,Laptop,Electronics,4,29881,119524
9998,9999,Ali,18,female,Aswan,Monitor,Electronics,2,11832,23664
9999,10000,Omar,44,female,Aswan,Mouse,Electronics,4,632,2528

In [41]:
valid_cities = ["Cairo","Alexandria","Giza","Aswan","Tanta","Mansoura","Luxor","Suez"]

In [42]:
df_clean[~df_clean["city"].isin(valid_cities)]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
3,4,Laila,65,male,paris,Monitor,Electronics,4,6621,26484

In [43]:
df_clean[df_clean["order_id"] == 4]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
3,4,Laila,65,male,paris,Monitor,Electronics,4,6621,26484

In [44]:
df_clean[df_clean["customer_name"] == "Laila"]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,42,male,Cairo,Headphones,Electronics,1,1760,1760
3,4,Laila,65,male,paris,Monitor,Electronics,4,6621,26484
4,5,Laila,39,female,Tanta,Headphones,Electronics,3,1366,4098
5,6,Laila,25,female,Giza,Headphones,Electronics,3,4212,12636
7,8,Laila,40,female,Alexandria,Laptop,Electronics,5,33297,166485
...,...,...,...,...,...,...,...,...,...,...
9977,9978,Laila,57,female,Aswan,Monitor,Electronics,2,9796,19592
9982,9983,Laila,19,male,Alexandria,Headphones,Electronics,1,4202,4202
9986,9987,Laila,35,female,Aswan,Laptop,Electronics,4,30974,123896
9993,9994,Laila,27,male,Luxor,Keyboard,Electronics,2,800,1600
9996,9997,Laila,58,male,Aswan,Keyboard,Electronics,3,510,1530

In [45]:
df_clean["customer_name"].value_counts()

customer_name
Laila      1290
Ali        1268
Ahmed      1264
Youseef    1263
Sara       1261
Omar       1225
Mona       1220
nada       1209
Name: count, dtype: int64

In [46]:
df_clean.columns

Index(['order_id', 'customer_name', 'customer_age', 'customer_gender', 'city',
       'product', 'category', 'quantity', 'unit_price', 'total_price'],
      dtype='str')

In [47]:
df_clean["order_id"].duplicated().sum()

np.int64(0)

In [48]:
df_clean[df_clean["unit_price"] < 0]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,-500,1290

In [49]:
df_clean[df_clean["product"] == "keyboard"]["unit_price"].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: unit_price, dtype: float64

In [50]:
df_clean["product"].value_counts()

product
Monitor       2021
Laptop        2015
Keyboard      2008
Headphones    1984
Mouse         1972
Name: count, dtype: int64

In [51]:
df_clean["product"].unique()

<StringArray>
['Headphones', 'Monitor', 'Keyboard', 'Laptop', 'Mouse']
Length: 5, dtype: str

In [52]:
df_clean[df_clean["product"] == "keyboard"]["unit_price"].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: unit_price, dtype: float64

In [53]:
df_clean["product"].unique().tolist()

['Headphones', 'Monitor', 'Keyboard', 'Laptop', 'Mouse']

In [54]:
df_clean["product"].unique().map(repr)

array(["'Headphones'", "'Monitor'", "'Keyboard'", "'Laptop'", "'Mouse'"],
      dtype=object)

In [55]:
[repr (x) for x in df_clean["product"].unique()]

["'Headphones'", "'Monitor'", "'Keyboard'", "'Laptop'", "'Mouse'"]

In [56]:
[(x, len(x)) for x in df_clean["product"].unique()]

[('Headphones', 10),
 ('Monitor', 7),
 ('Keyboard', 8),
 ('Laptop', 6),
 ('Mouse', 5)]

In [57]:
df_clean[df_clean["product"] == "keyboard"]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [58]:
df_clean.loc[df_clean["product"] == "Keyboard", ["order_id", "product", "quantity", "unit_price", "total_price"]].head(10)

    order_id   product  quantity  unit_price  total_price
2          3  Keyboard         1        -500         1290
8          9  Keyboard         2        1165         2330
13        14  Keyboard         4         802         3208
16        17  Keyboard         3        1746         5238
20        21  Keyboard         2        1870         3740
21        22  Keyboard         3        1590         4770
29        30  Keyboard         2        1636         3272
33        34  Keyboard         1        1331         1331
40        41  Keyboard         5         483         2415
41        42  Keyboard         2        1697         3394

In [59]:
df_clean[df_clean["product"] == "Keyboard"].value_counts()

order_id  customer_name  customer_age  customer_gender  city        product   category     quantity  unit_price  total_price
3         Ali            61            female           Suez        Keyboard  Electronics  1         -500        1290           1
9         Ahmed          25            female           Giza        Keyboard  Electronics  2          1165       2330           1
14        Ali            35            female           Giza        Keyboard  Electronics  4          802        3208           1
17        Ali            53            male             Giza        Keyboard  Electronics  3          1746       5238           1
21        Mona           18            male             Suez        Keyboard  Electronics  2          1870       3740           1
                                                                                                                               ..
9982      Omar           34            female           Alexandria  Keyboard  Electronics  3          1393       4179           1
9986      nada           28            female           Tanta       Keyboard  Electronics  2          1456       2912           1
9993      nada           19            male             Aswan       Keyboard  Electronics  1          1409       1409           1
9994      Laila          27            male             Luxor       Keyboard  Electronics  2          800        1600           1
9997      Laila          58            male             Aswan       Keyboard  Electronics  3          510        1530           1
Name: count, Length: 2008, dtype: int64

In [60]:
df_clean[df_clean["product"] == "Keyboard"]["unit_price"].describe()

count    2008.000000
mean     1208.034363
std       469.929083
min      -500.000000
25%       808.750000
50%      1199.500000
75%      1632.250000
max      1999.000000
Name: unit_price, dtype: float64

In [61]:
keyboard_median = df_clean.loc[
    (df_clean["product"] == "Keyboard") &
    (df_clean["unit_price"] >= 0),
    "unit_price"
    ].median()
keyboard_median

np.float64(1200.0)

In [62]:
df_clean.loc[
    df_clean["order_id"] == 3,
    ["order_id", "product", "quantity", "unit_price", "total_price"]
    ]

   order_id   product  quantity  unit_price  total_price
2         3  Keyboard         1        -500         1290

In [63]:
df_clean.loc[
    (df_clean["product"] == "Keyboard") &
    (df_clean["unit_price"] >= 0),
    "unit_price"
    ].describe()

count    2007.000000
mean     1208.885401
std       468.495866
min       400.000000
25%       809.000000
50%      1200.000000
75%      1632.500000
max      1999.000000
Name: unit_price, dtype: float64

In [64]:
df_clean.loc[
    df_clean["order_id"] == 3,
    "total_price"
    ] / df_clean.loc[
        df_clean["order_id"] == 3,
        "quantity"
        ]

2    1290.0
dtype: float64

In [31]:
df_clean.loc[df_clean["order_id"] == 3, "unit_price"] = 1290

In [32]:
df_clean.loc[df_clean["order_id"] == 3,
    ["order_id", "product", "quantity", "unit_price", "total_price"]]

   order_id   product  quantity  unit_price  total_price
2         3  Keyboard         1        1290         1290

In [33]:
df_clean[df_clean["unit_price"] < 0]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [34]:
df_clean[
    df_clean["total_price"] !=
    df_clean["unit_price"] * df_clean["quantity"]]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []